consolidate-commits = true
consolidate-pushes = true
dev-version = true
dev-version-ext = "dev"
pre-release-hook = "./scripts/release_hook"
shared-version = true
tag-prefix = ""
tag-name = "v{{version}}"
