name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format_build_test:
    name: Format, build, & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.58.0
    steps:
      # https://github.com/actions/virtual-environments/issues/264#issuecomment-966491739
      - name: Install zsh
        run: sudo apt-get update && sudo apt-get install zsh
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: clippy, rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1
      - name: Install tools
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: just cargo-tarpaulin
      - name: Check format
        if: ${{ matrix.rust == 'stable' }}
        run: just ci-format
      - name: Build and lint on stable
        if: ${{ matrix.rust == 'stable' }}
        run: just ci-build-lint
      - name: Build on non-stable toolchains
        if: ${{ matrix.rust != 'stable' }}
        run: just ci-build-only
      - name: Run tests and generate coverage report
        run: just ci-test
      - name: Upload to codecov.io
        if: ${{ matrix.rust == 'stable' }}
        uses: codecov/codecov-action@v2
        with:
          directory: target/coverage
          fail_ci_if_error: true
